name: quatrex
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - alsa-lib=1.2.12
  - annotated-types=0.6.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=23.1.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.8.0
  - blacken-docs=1.18.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - cfgv=3.3.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.0.5
  - coverage=7.6.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.8
  - docutils=0.21.2
  - double-conversion=3.3.0
  - execnet=2.1.1
  - executing=0.8.3
  - expat=2.6.2
  - fastrlock=0.8.2
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.14
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - harfbuzz=8.5.0
  - icu=73.2
  - identify=2.6.0
  - idna=3.7
  - imagesize=1.4.1
  - iniconfig=1.1.1
  - ipykernel=6.28.0
  - ipympl=0.8.7
  - ipython=8.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=1.0.0
  - just=1.35.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcups=2.3.3
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.8
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=255
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mpg123=1.32.6
  - mypy_extensions=1.0.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nodeenv=1.9.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.100
  - numpy=2.1.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre2=10.43
  - pexpect=4.8.0
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - pre-commit=3.8.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyside6=6.7.1
  - pysocks=1.7.1
  - pytest=7.4.4
  - pytest-cov=5.0.0
  - pytest-mpi=0.6
  - pytest-xdist=3.6.1
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.8
  - qt6-main=6.7.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruff=0.6.1
  - scipy=1.14.0
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=8.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - virtualenv=20.26.3
  - wayland=1.23.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=3.6.6
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
